global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'evaluation-backend-metrics'
    static_configs:
      - targets: ['host.docker.internal:8000']  # Changed from evaluation-backend:8000
    scrape_interval: 5s
    metrics_path: /metrics

  - job_name: 'evaluation-backend-health'
    static_configs:
      - targets: ['host.docker.internal:8000']  # Changed from evaluation-backend:8000
    scrape_interval: 30s
    metrics_path: /health